[2023-01-04 06:10:59,459] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: populate_crypto_values.get_crypto_values scheduled__2021-09-01T07:00:00+00:00 [queued]>
[2023-01-04 06:10:59,467] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: populate_crypto_values.get_crypto_values scheduled__2021-09-01T07:00:00+00:00 [queued]>
[2023-01-04 06:10:59,467] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-01-04 06:10:59,467] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2023-01-04 06:10:59,468] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-01-04 06:10:59,480] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): get_crypto_values> on 2021-09-01 07:00:00+00:00
[2023-01-04 06:10:59,484] {standard_task_runner.py:52} INFO - Started process 17383 to run task
[2023-01-04 06:10:59,490] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'populate_crypto_values', 'get_crypto_values', 'scheduled__2021-09-01T07:00:00+00:00', '--job-id', '301', '--raw', '--subdir', 'DAGS_FOLDER/populate_crypto_values.py', '--cfg-path', '/tmp/tmpbtzn9ixb', '--error-file', '/tmp/tmpuhi5bftz']
[2023-01-04 06:10:59,491] {standard_task_runner.py:80} INFO - Job 301: Subtask get_crypto_values
[2023-01-04 06:10:59,544] {task_command.py:370} INFO - Running <TaskInstance: populate_crypto_values.get_crypto_values scheduled__2021-09-01T07:00:00+00:00 [running]> on host xuxon-virtual-machine
[2023-01-04 06:10:59,613] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=populate_crypto_values
AIRFLOW_CTX_TASK_ID=get_crypto_values
AIRFLOW_CTX_EXECUTION_DATE=2021-09-01T07:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-09-01T07:00:00+00:00
[2023-01-04 06:11:30,289] {logging_mixin.py:115} INFO - Attempt 1 to get the crypto values has failed. The api status was 503
[2023-01-04 06:11:30,289] {logging_mixin.py:115} INFO - The api response was {"status":503,"error":"Service Unavailable"}
[2023-01-04 06:11:45,989] {logging_mixin.py:115} INFO - New rows have been added.
[2023-01-04 06:11:45,990] {python.py:173} INFO - Done. Returned value was: None
[2023-01-04 06:11:45,997] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=populate_crypto_values, task_id=get_crypto_values, execution_date=20210901T070000, start_date=20230104T091059, end_date=20230104T091145
[2023-01-04 06:11:46,040] {local_task_job.py:156} INFO - Task exited with return code 0
[2023-01-04 06:11:46,051] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
