[2023-01-04 13:04:27,035] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: populate_crypto_values.get_crypto_values scheduled__2022-04-04T07:00:00+00:00 [queued]>
[2023-01-04 13:04:27,042] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: populate_crypto_values.get_crypto_values scheduled__2022-04-04T07:00:00+00:00 [queued]>
[2023-01-04 13:04:27,042] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-01-04 13:04:27,042] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2023-01-04 13:04:27,042] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-01-04 13:04:27,054] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): get_crypto_values> on 2022-04-04 07:00:00+00:00
[2023-01-04 13:04:27,058] {standard_task_runner.py:52} INFO - Started process 27342 to run task
[2023-01-04 13:04:27,063] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'populate_crypto_values', 'get_crypto_values', 'scheduled__2022-04-04T07:00:00+00:00', '--job-id', '519', '--raw', '--subdir', 'DAGS_FOLDER/populate_crypto_values.py', '--cfg-path', '/tmp/tmp98tcb507', '--error-file', '/tmp/tmpjiicjyd_']
[2023-01-04 13:04:27,064] {standard_task_runner.py:80} INFO - Job 519: Subtask get_crypto_values
[2023-01-04 13:04:27,113] {task_command.py:370} INFO - Running <TaskInstance: populate_crypto_values.get_crypto_values scheduled__2022-04-04T07:00:00+00:00 [running]> on host xuxon-virtual-machine
[2023-01-04 13:04:27,179] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=populate_crypto_values
AIRFLOW_CTX_TASK_ID=get_crypto_values
AIRFLOW_CTX_EXECUTION_DATE=2022-04-04T07:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-04-04T07:00:00+00:00
[2023-01-04 13:04:27,274] {logging_mixin.py:115} INFO - Attempt 1 to get the crypto values has failed. The api status was 429
[2023-01-04 13:04:27,275] {logging_mixin.py:115} INFO - The api response was {"status":{"error_code":429,"error_message":"You've exceeded the Rate Limit. Please visit https://www.coingecko.com/en/api/pricing to subscribe to our API plans for higher rate limits."}}
[2023-01-04 13:04:42,446] {logging_mixin.py:115} INFO - Attempt 2 to get the crypto values has failed. The api status was 429
[2023-01-04 13:04:42,446] {logging_mixin.py:115} INFO - The api response was {"status":{"error_code":429,"error_message":"You've exceeded the Rate Limit. Please visit https://www.coingecko.com/en/api/pricing to subscribe to our API plans for higher rate limits."}}
[2023-01-04 13:04:57,553] {logging_mixin.py:115} INFO - Attempt 3 to get the crypto values has failed. The api status was 429
[2023-01-04 13:04:57,554] {logging_mixin.py:115} INFO - The api response was {"status":{"error_code":429,"error_message":"You've exceeded the Rate Limit. Please visit https://www.coingecko.com/en/api/pricing to subscribe to our API plans for higher rate limits."}}
[2023-01-04 13:05:12,686] {logging_mixin.py:115} INFO - Attempt 4 to get the crypto values has failed. The api status was 429
[2023-01-04 13:05:12,687] {logging_mixin.py:115} INFO - The api response was {"status":{"error_code":429,"error_message":"You've exceeded the Rate Limit. Please visit https://www.coingecko.com/en/api/pricing to subscribe to our API plans for higher rate limits."}}
[2023-01-04 13:05:27,827] {logging_mixin.py:115} INFO - Attempt 5 to get the crypto values has failed. The api status was 429
[2023-01-04 13:05:27,827] {logging_mixin.py:115} INFO - The api response was {"status":{"error_code":429,"error_message":"You've exceeded the Rate Limit. Please visit https://www.coingecko.com/en/api/pricing to subscribe to our API plans for higher rate limits."}}
[2023-01-04 13:05:42,966] {logging_mixin.py:115} INFO - Attempt 6 to get the crypto values has failed. The api status was 429
[2023-01-04 13:05:42,967] {logging_mixin.py:115} INFO - The api response was {"status":{"error_code":429,"error_message":"You've exceeded the Rate Limit. Please visit https://www.coingecko.com/en/api/pricing to subscribe to our API plans for higher rate limits."}}
[2023-01-04 13:05:58,111] {logging_mixin.py:115} INFO - Attempt 7 to get the crypto values has failed. The api status was 429
[2023-01-04 13:05:58,113] {logging_mixin.py:115} INFO - The api response was {"status":{"error_code":429,"error_message":"You've exceeded the Rate Limit. Please visit https://www.coingecko.com/en/api/pricing to subscribe to our API plans for higher rate limits."}}
[2023-01-04 13:06:13,334] {logging_mixin.py:115} INFO - Attempt 8 to get the crypto values has failed. The api status was 429
[2023-01-04 13:06:13,335] {logging_mixin.py:115} INFO - The api response was {"status":{"error_code":429,"error_message":"You've exceeded the Rate Limit. Please visit https://www.coingecko.com/en/api/pricing to subscribe to our API plans for higher rate limits."}}
[2023-01-04 13:06:29,924] {logging_mixin.py:115} INFO - New rows have been added.
[2023-01-04 13:06:29,926] {python.py:173} INFO - Done. Returned value was: None
[2023-01-04 13:06:29,951] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=populate_crypto_values, task_id=get_crypto_values, execution_date=20220404T070000, start_date=20230104T160427, end_date=20230104T160629
[2023-01-04 13:06:30,054] {local_task_job.py:156} INFO - Task exited with return code 0
[2023-01-04 13:06:30,103] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
