[2023-01-04 12:50:25,964] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: populate_crypto_values.get_crypto_values scheduled__2022-02-13T07:00:00+00:00 [queued]>
[2023-01-04 12:50:25,970] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: populate_crypto_values.get_crypto_values scheduled__2022-02-13T07:00:00+00:00 [queued]>
[2023-01-04 12:50:25,971] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-01-04 12:50:25,971] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2023-01-04 12:50:25,971] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-01-04 12:50:25,988] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): get_crypto_values> on 2022-02-13 07:00:00+00:00
[2023-01-04 12:50:25,992] {standard_task_runner.py:52} INFO - Started process 25916 to run task
[2023-01-04 12:50:25,997] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'populate_crypto_values', 'get_crypto_values', 'scheduled__2022-02-13T07:00:00+00:00', '--job-id', '469', '--raw', '--subdir', 'DAGS_FOLDER/populate_crypto_values.py', '--cfg-path', '/tmp/tmpepcv1u4p', '--error-file', '/tmp/tmpd7_evr08']
[2023-01-04 12:50:25,998] {standard_task_runner.py:80} INFO - Job 469: Subtask get_crypto_values
[2023-01-04 12:50:26,049] {task_command.py:370} INFO - Running <TaskInstance: populate_crypto_values.get_crypto_values scheduled__2022-02-13T07:00:00+00:00 [running]> on host xuxon-virtual-machine
[2023-01-04 12:50:26,105] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=populate_crypto_values
AIRFLOW_CTX_TASK_ID=get_crypto_values
AIRFLOW_CTX_EXECUTION_DATE=2022-02-13T07:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-02-13T07:00:00+00:00
[2023-01-04 12:50:26,199] {logging_mixin.py:115} INFO - Attempt 1 to get the crypto values has failed. The api status was 429
[2023-01-04 12:50:26,200] {logging_mixin.py:115} INFO - The api response was {"status":{"error_code":429,"error_message":"You've exceeded the Rate Limit. Please visit https://www.coingecko.com/en/api/pricing to subscribe to our API plans for higher rate limits."}}
[2023-01-04 12:50:41,318] {logging_mixin.py:115} INFO - Attempt 2 to get the crypto values has failed. The api status was 429
[2023-01-04 12:50:41,319] {logging_mixin.py:115} INFO - The api response was {"status":{"error_code":429,"error_message":"You've exceeded the Rate Limit. Please visit https://www.coingecko.com/en/api/pricing to subscribe to our API plans for higher rate limits."}}
[2023-01-04 12:50:56,539] {logging_mixin.py:115} INFO - Attempt 3 to get the crypto values has failed. The api status was 429
[2023-01-04 12:50:56,540] {logging_mixin.py:115} INFO - The api response was {"status":{"error_code":429,"error_message":"You've exceeded the Rate Limit. Please visit https://www.coingecko.com/en/api/pricing to subscribe to our API plans for higher rate limits."}}
[2023-01-04 12:51:11,667] {logging_mixin.py:115} INFO - Attempt 4 to get the crypto values has failed. The api status was 429
[2023-01-04 12:51:11,668] {logging_mixin.py:115} INFO - The api response was {"status":{"error_code":429,"error_message":"You've exceeded the Rate Limit. Please visit https://www.coingecko.com/en/api/pricing to subscribe to our API plans for higher rate limits."}}
[2023-01-04 12:51:26,792] {logging_mixin.py:115} INFO - Attempt 5 to get the crypto values has failed. The api status was 429
[2023-01-04 12:51:26,792] {logging_mixin.py:115} INFO - The api response was {"status":{"error_code":429,"error_message":"You've exceeded the Rate Limit. Please visit https://www.coingecko.com/en/api/pricing to subscribe to our API plans for higher rate limits."}}
[2023-01-04 12:51:41,909] {logging_mixin.py:115} INFO - Attempt 6 to get the crypto values has failed. The api status was 429
[2023-01-04 12:51:41,909] {logging_mixin.py:115} INFO - The api response was {"status":{"error_code":429,"error_message":"You've exceeded the Rate Limit. Please visit https://www.coingecko.com/en/api/pricing to subscribe to our API plans for higher rate limits."}}
[2023-01-04 12:51:57,043] {logging_mixin.py:115} INFO - Attempt 7 to get the crypto values has failed. The api status was 429
[2023-01-04 12:51:57,044] {logging_mixin.py:115} INFO - The api response was {"status":{"error_code":429,"error_message":"You've exceeded the Rate Limit. Please visit https://www.coingecko.com/en/api/pricing to subscribe to our API plans for higher rate limits."}}
[2023-01-04 12:52:12,190] {logging_mixin.py:115} INFO - Attempt 8 to get the crypto values has failed. The api status was 429
[2023-01-04 12:52:12,190] {logging_mixin.py:115} INFO - The api response was {"status":{"error_code":429,"error_message":"You've exceeded the Rate Limit. Please visit https://www.coingecko.com/en/api/pricing to subscribe to our API plans for higher rate limits."}}
[2023-01-04 12:52:28,286] {logging_mixin.py:115} INFO - New rows have been added.
[2023-01-04 12:52:28,287] {python.py:173} INFO - Done. Returned value was: None
[2023-01-04 12:52:28,303] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=populate_crypto_values, task_id=get_crypto_values, execution_date=20220213T070000, start_date=20230104T155025, end_date=20230104T155228
[2023-01-04 12:52:28,358] {local_task_job.py:156} INFO - Task exited with return code 0
[2023-01-04 12:52:28,376] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
