[2023-01-04 13:39:34,093] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: populate_crypto_values.get_crypto_values scheduled__2022-08-26T07:00:00+00:00 [queued]>
[2023-01-04 13:39:34,099] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: populate_crypto_values.get_crypto_values scheduled__2022-08-26T07:00:00+00:00 [queued]>
[2023-01-04 13:39:34,100] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-01-04 13:39:34,100] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2023-01-04 13:39:34,100] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-01-04 13:39:34,112] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): get_crypto_values> on 2022-08-26 07:00:00+00:00
[2023-01-04 13:39:34,116] {standard_task_runner.py:52} INFO - Started process 31107 to run task
[2023-01-04 13:39:34,122] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'populate_crypto_values', 'get_crypto_values', 'scheduled__2022-08-26T07:00:00+00:00', '--job-id', '663', '--raw', '--subdir', 'DAGS_FOLDER/populate_crypto_values.py', '--cfg-path', '/tmp/tmpbs0cmowd', '--error-file', '/tmp/tmpa7mabmcx']
[2023-01-04 13:39:34,123] {standard_task_runner.py:80} INFO - Job 663: Subtask get_crypto_values
[2023-01-04 13:39:34,174] {task_command.py:370} INFO - Running <TaskInstance: populate_crypto_values.get_crypto_values scheduled__2022-08-26T07:00:00+00:00 [running]> on host xuxon-virtual-machine
[2023-01-04 13:39:34,433] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=populate_crypto_values
AIRFLOW_CTX_TASK_ID=get_crypto_values
AIRFLOW_CTX_EXECUTION_DATE=2022-08-26T07:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-08-26T07:00:00+00:00
[2023-01-04 13:39:35,141] {logging_mixin.py:115} INFO - Attempt 1 to get the crypto values has failed. The api status was 429
[2023-01-04 13:39:35,142] {logging_mixin.py:115} INFO - The api response was {"status":{"error_code":429,"error_message":"You've exceeded the Rate Limit. Please visit https://www.coingecko.com/en/api/pricing to subscribe to our API plans for higher rate limits."}}
[2023-01-04 13:39:50,252] {logging_mixin.py:115} INFO - Attempt 2 to get the crypto values has failed. The api status was 429
[2023-01-04 13:39:50,253] {logging_mixin.py:115} INFO - The api response was {"status":{"error_code":429,"error_message":"You've exceeded the Rate Limit. Please visit https://www.coingecko.com/en/api/pricing to subscribe to our API plans for higher rate limits."}}
[2023-01-04 13:40:05,372] {logging_mixin.py:115} INFO - Attempt 3 to get the crypto values has failed. The api status was 429
[2023-01-04 13:40:05,373] {logging_mixin.py:115} INFO - The api response was {"status":{"error_code":429,"error_message":"You've exceeded the Rate Limit. Please visit https://www.coingecko.com/en/api/pricing to subscribe to our API plans for higher rate limits."}}
[2023-01-04 13:40:20,523] {logging_mixin.py:115} INFO - Attempt 4 to get the crypto values has failed. The api status was 429
[2023-01-04 13:40:20,524] {logging_mixin.py:115} INFO - The api response was {"status":{"error_code":429,"error_message":"You've exceeded the Rate Limit. Please visit https://www.coingecko.com/en/api/pricing to subscribe to our API plans for higher rate limits."}}
[2023-01-04 13:40:35,662] {logging_mixin.py:115} INFO - Attempt 5 to get the crypto values has failed. The api status was 429
[2023-01-04 13:40:35,663] {logging_mixin.py:115} INFO - The api response was {"status":{"error_code":429,"error_message":"You've exceeded the Rate Limit. Please visit https://www.coingecko.com/en/api/pricing to subscribe to our API plans for higher rate limits."}}
[2023-01-04 13:40:50,800] {logging_mixin.py:115} INFO - Attempt 6 to get the crypto values has failed. The api status was 429
[2023-01-04 13:40:50,802] {logging_mixin.py:115} INFO - The api response was {"status":{"error_code":429,"error_message":"You've exceeded the Rate Limit. Please visit https://www.coingecko.com/en/api/pricing to subscribe to our API plans for higher rate limits."}}
[2023-01-04 13:41:05,908] {logging_mixin.py:115} INFO - Attempt 7 to get the crypto values has failed. The api status was 429
[2023-01-04 13:41:05,909] {logging_mixin.py:115} INFO - The api response was {"status":{"error_code":429,"error_message":"You've exceeded the Rate Limit. Please visit https://www.coingecko.com/en/api/pricing to subscribe to our API plans for higher rate limits."}}
[2023-01-04 13:41:21,037] {logging_mixin.py:115} INFO - Attempt 8 to get the crypto values has failed. The api status was 429
[2023-01-04 13:41:21,039] {logging_mixin.py:115} INFO - The api response was {"status":{"error_code":429,"error_message":"You've exceeded the Rate Limit. Please visit https://www.coingecko.com/en/api/pricing to subscribe to our API plans for higher rate limits."}}
[2023-01-04 13:41:36,923] {logging_mixin.py:115} INFO - New rows have been added.
[2023-01-04 13:41:36,924] {python.py:173} INFO - Done. Returned value was: None
[2023-01-04 13:41:36,979] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=populate_crypto_values, task_id=get_crypto_values, execution_date=20220826T070000, start_date=20230104T163934, end_date=20230104T164136
[2023-01-04 13:41:37,018] {local_task_job.py:156} INFO - Task exited with return code 0
[2023-01-04 13:41:37,030] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
