[2023-01-04 03:46:33,938] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: populate_crypto_values.get_crypto_values scheduled__2021-01-03T07:00:00+00:00 [queued]>
[2023-01-04 03:46:33,944] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: populate_crypto_values.get_crypto_values scheduled__2021-01-03T07:00:00+00:00 [queued]>
[2023-01-04 03:46:33,944] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-01-04 03:46:33,945] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2023-01-04 03:46:33,945] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-01-04 03:46:34,137] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): get_crypto_values> on 2021-01-03 07:00:00+00:00
[2023-01-04 03:46:34,227] {standard_task_runner.py:52} INFO - Started process 58220 to run task
[2023-01-04 03:46:34,592] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'populate_crypto_values', 'get_crypto_values', 'scheduled__2021-01-03T07:00:00+00:00', '--job-id', '31', '--raw', '--subdir', 'DAGS_FOLDER/populate_crypto_values.py', '--cfg-path', '/tmp/tmp3es1v1mo', '--error-file', '/tmp/tmps5g4m9l5']
[2023-01-04 03:46:34,593] {standard_task_runner.py:80} INFO - Job 31: Subtask get_crypto_values
[2023-01-04 03:46:36,332] {task_command.py:370} INFO - Running <TaskInstance: populate_crypto_values.get_crypto_values scheduled__2021-01-03T07:00:00+00:00 [running]> on host xuxon-virtual-machine
[2023-01-04 03:46:37,208] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=populate_crypto_values
AIRFLOW_CTX_TASK_ID=get_crypto_values
AIRFLOW_CTX_EXECUTION_DATE=2021-01-03T07:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-01-03T07:00:00+00:00
[2023-01-04 03:46:38,406] {logging_mixin.py:115} INFO - New rows have been added.
[2023-01-04 03:46:38,407] {python.py:173} INFO - Done. Returned value was: None
[2023-01-04 03:46:38,442] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=populate_crypto_values, task_id=get_crypto_values, execution_date=20210103T070000, start_date=20230104T064633, end_date=20230104T064638
[2023-01-04 03:46:38,489] {local_task_job.py:156} INFO - Task exited with return code 0
[2023-01-04 03:46:38,536] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-01-04 04:11:58,169] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: populate_crypto_values.get_crypto_values scheduled__2021-01-03T07:00:00+00:00 [queued]>
[2023-01-04 04:11:58,278] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: populate_crypto_values.get_crypto_values scheduled__2021-01-03T07:00:00+00:00 [queued]>
[2023-01-04 04:11:58,279] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-01-04 04:11:58,279] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2023-01-04 04:11:58,279] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-01-04 04:11:58,307] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): get_crypto_values> on 2021-01-03 07:00:00+00:00
[2023-01-04 04:11:58,313] {standard_task_runner.py:52} INFO - Started process 62279 to run task
[2023-01-04 04:11:58,319] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'populate_crypto_values', 'get_crypto_values', 'scheduled__2021-01-03T07:00:00+00:00', '--job-id', '31', '--raw', '--subdir', 'DAGS_FOLDER/populate_crypto_values.py', '--cfg-path', '/tmp/tmpcp4y7bin', '--error-file', '/tmp/tmp2ual35n5']
[2023-01-04 04:11:58,320] {standard_task_runner.py:80} INFO - Job 31: Subtask get_crypto_values
[2023-01-04 04:11:58,378] {task_command.py:370} INFO - Running <TaskInstance: populate_crypto_values.get_crypto_values scheduled__2021-01-03T07:00:00+00:00 [running]> on host xuxon-virtual-machine
[2023-01-04 04:11:58,450] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=populate_crypto_values
AIRFLOW_CTX_TASK_ID=get_crypto_values
AIRFLOW_CTX_EXECUTION_DATE=2021-01-03T07:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-01-03T07:00:00+00:00
[2023-01-04 04:11:59,567] {logging_mixin.py:115} INFO - Encountered errors while inserting rows: [{'index': 0, 'errors': [{'reason': 'invalid', 'location': 'snapshot_date', 'debugInfo': '', 'message': "Invalid date: '04-01-2021'"}]}, {'index': 1, 'errors': [{'reason': 'invalid', 'location': 'snapshot_date', 'debugInfo': '', 'message': "Invalid date: '04-01-2021'"}]}]
[2023-01-04 04:11:59,568] {python.py:173} INFO - Done. Returned value was: None
[2023-01-04 04:11:59,592] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=populate_crypto_values, task_id=get_crypto_values, execution_date=20210103T070000, start_date=20230104T071158, end_date=20230104T071159
[2023-01-04 04:11:59,626] {local_task_job.py:156} INFO - Task exited with return code 0
[2023-01-04 04:11:59,646] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-01-04 05:07:40,804] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: populate_crypto_values.get_crypto_values scheduled__2021-01-03T07:00:00+00:00 [queued]>
[2023-01-04 05:07:40,827] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: populate_crypto_values.get_crypto_values scheduled__2021-01-03T07:00:00+00:00 [queued]>
[2023-01-04 05:07:40,828] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-01-04 05:07:40,828] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2023-01-04 05:07:40,828] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-01-04 05:07:40,851] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): get_crypto_values> on 2021-01-03 07:00:00+00:00
[2023-01-04 05:07:40,858] {standard_task_runner.py:52} INFO - Started process 5344 to run task
[2023-01-04 05:07:40,867] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'populate_crypto_values', 'get_crypto_values', 'scheduled__2021-01-03T07:00:00+00:00', '--job-id', '58', '--raw', '--subdir', 'DAGS_FOLDER/populate_crypto_values.py', '--cfg-path', '/tmp/tmp2aqmy064', '--error-file', '/tmp/tmpt9s959w7']
[2023-01-04 05:07:40,869] {standard_task_runner.py:80} INFO - Job 58: Subtask get_crypto_values
[2023-01-04 05:07:40,939] {task_command.py:370} INFO - Running <TaskInstance: populate_crypto_values.get_crypto_values scheduled__2021-01-03T07:00:00+00:00 [running]> on host xuxon-virtual-machine
[2023-01-04 05:07:41,001] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=populate_crypto_values
AIRFLOW_CTX_TASK_ID=get_crypto_values
AIRFLOW_CTX_EXECUTION_DATE=2021-01-03T07:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-01-03T07:00:00+00:00
[2023-01-04 05:07:41,984] {logging_mixin.py:115} INFO - Encountered errors while inserting rows: [{'index': 0, 'errors': [{'reason': 'invalid', 'location': 'snapshot_date', 'debugInfo': '', 'message': "Invalid date: '04-01-2021'"}]}, {'index': 1, 'errors': [{'reason': 'invalid', 'location': 'snapshot_date', 'debugInfo': '', 'message': "Invalid date: '04-01-2021'"}]}]
[2023-01-04 05:07:41,985] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/xuxon/Documents/airflow_case/venv/lib/python3.8/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/xuxon/Documents/airflow_case/venv/lib/python3.8/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/xuxon/Documents/airflow_case/dags/populate_crypto_values.py", line 87, in get_crypto_values_func
    raise Exception('Could not insert the values for this date')
Exception: Could not insert the values for this date
[2023-01-04 05:07:42,002] {taskinstance.py:1395} INFO - Marking task as FAILED. dag_id=populate_crypto_values, task_id=get_crypto_values, execution_date=20210103T070000, start_date=20230104T080740, end_date=20230104T080741
[2023-01-04 05:07:42,029] {standard_task_runner.py:92} ERROR - Failed to execute job 58 for task get_crypto_values (Could not insert the values for this date; 5344)
[2023-01-04 05:07:42,073] {local_task_job.py:156} INFO - Task exited with return code 1
[2023-01-04 05:07:42,112] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-01-04 05:11:38,810] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: populate_crypto_values.get_crypto_values scheduled__2021-01-03T07:00:00+00:00 [queued]>
[2023-01-04 05:11:38,820] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: populate_crypto_values.get_crypto_values scheduled__2021-01-03T07:00:00+00:00 [queued]>
[2023-01-04 05:11:38,821] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-01-04 05:11:38,821] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2023-01-04 05:11:38,821] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-01-04 05:11:38,839] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): get_crypto_values> on 2021-01-03 07:00:00+00:00
[2023-01-04 05:11:38,858] {standard_task_runner.py:52} INFO - Started process 6567 to run task
[2023-01-04 05:11:38,956] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'populate_crypto_values', 'get_crypto_values', 'scheduled__2021-01-03T07:00:00+00:00', '--job-id', '60', '--raw', '--subdir', 'DAGS_FOLDER/populate_crypto_values.py', '--cfg-path', '/tmp/tmpzkdez408', '--error-file', '/tmp/tmp5aj5i05o']
[2023-01-04 05:11:38,958] {standard_task_runner.py:80} INFO - Job 60: Subtask get_crypto_values
[2023-01-04 05:11:39,198] {task_command.py:370} INFO - Running <TaskInstance: populate_crypto_values.get_crypto_values scheduled__2021-01-03T07:00:00+00:00 [running]> on host xuxon-virtual-machine
[2023-01-04 05:11:39,366] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=populate_crypto_values
AIRFLOW_CTX_TASK_ID=get_crypto_values
AIRFLOW_CTX_EXECUTION_DATE=2021-01-03T07:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-01-03T07:00:00+00:00
[2023-01-04 05:11:40,615] {logging_mixin.py:115} INFO - New rows have been added.
[2023-01-04 05:11:40,616] {python.py:173} INFO - Done. Returned value was: None
[2023-01-04 05:11:40,623] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=populate_crypto_values, task_id=get_crypto_values, execution_date=20210103T070000, start_date=20230104T081138, end_date=20230104T081140
[2023-01-04 05:11:40,673] {local_task_job.py:156} INFO - Task exited with return code 0
[2023-01-04 05:11:40,702] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
