[2023-01-04 03:46:22,839] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: populate_crypto_values.get_crypto_values scheduled__2021-01-02T07:00:00+00:00 [queued]>
[2023-01-04 03:46:22,844] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: populate_crypto_values.get_crypto_values scheduled__2021-01-02T07:00:00+00:00 [queued]>
[2023-01-04 03:46:22,845] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-01-04 03:46:22,845] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2023-01-04 03:46:22,845] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-01-04 03:46:23,077] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): get_crypto_values> on 2021-01-02 07:00:00+00:00
[2023-01-04 03:46:23,083] {standard_task_runner.py:52} INFO - Started process 58178 to run task
[2023-01-04 03:46:23,120] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'populate_crypto_values', 'get_crypto_values', 'scheduled__2021-01-02T07:00:00+00:00', '--job-id', '30', '--raw', '--subdir', 'DAGS_FOLDER/populate_crypto_values.py', '--cfg-path', '/tmp/tmpwprvocp0', '--error-file', '/tmp/tmpgrpmpnao']
[2023-01-04 03:46:23,121] {standard_task_runner.py:80} INFO - Job 30: Subtask get_crypto_values
[2023-01-04 03:46:23,828] {task_command.py:370} INFO - Running <TaskInstance: populate_crypto_values.get_crypto_values scheduled__2021-01-02T07:00:00+00:00 [running]> on host xuxon-virtual-machine
[2023-01-04 03:46:24,501] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=populate_crypto_values
AIRFLOW_CTX_TASK_ID=get_crypto_values
AIRFLOW_CTX_EXECUTION_DATE=2021-01-02T07:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-01-02T07:00:00+00:00
[2023-01-04 03:46:25,955] {logging_mixin.py:115} INFO - New rows have been added.
[2023-01-04 03:46:25,955] {python.py:173} INFO - Done. Returned value was: None
[2023-01-04 03:46:26,027] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=populate_crypto_values, task_id=get_crypto_values, execution_date=20210102T070000, start_date=20230104T064622, end_date=20230104T064626
[2023-01-04 03:46:26,107] {local_task_job.py:156} INFO - Task exited with return code 0
[2023-01-04 03:46:26,146] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-01-04 04:11:52,802] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: populate_crypto_values.get_crypto_values scheduled__2021-01-02T07:00:00+00:00 [queued]>
[2023-01-04 04:11:52,822] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: populate_crypto_values.get_crypto_values scheduled__2021-01-02T07:00:00+00:00 [queued]>
[2023-01-04 04:11:52,823] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-01-04 04:11:52,823] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2023-01-04 04:11:52,823] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-01-04 04:11:52,838] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): get_crypto_values> on 2021-01-02 07:00:00+00:00
[2023-01-04 04:11:52,844] {standard_task_runner.py:52} INFO - Started process 62247 to run task
[2023-01-04 04:11:52,856] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'populate_crypto_values', 'get_crypto_values', 'scheduled__2021-01-02T07:00:00+00:00', '--job-id', '30', '--raw', '--subdir', 'DAGS_FOLDER/populate_crypto_values.py', '--cfg-path', '/tmp/tmp1_4pr2kq', '--error-file', '/tmp/tmpwtgvw3u5']
[2023-01-04 04:11:52,858] {standard_task_runner.py:80} INFO - Job 30: Subtask get_crypto_values
[2023-01-04 04:11:52,968] {task_command.py:370} INFO - Running <TaskInstance: populate_crypto_values.get_crypto_values scheduled__2021-01-02T07:00:00+00:00 [running]> on host xuxon-virtual-machine
[2023-01-04 04:11:53,050] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=populate_crypto_values
AIRFLOW_CTX_TASK_ID=get_crypto_values
AIRFLOW_CTX_EXECUTION_DATE=2021-01-02T07:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-01-02T07:00:00+00:00
[2023-01-04 04:11:53,828] {logging_mixin.py:115} INFO - Encountered errors while inserting rows: [{'index': 0, 'errors': [{'reason': 'invalid', 'location': 'snapshot_date', 'debugInfo': '', 'message': "Invalid date: '03-01-2021'"}]}, {'index': 1, 'errors': [{'reason': 'invalid', 'location': 'snapshot_date', 'debugInfo': '', 'message': "Invalid date: '03-01-2021'"}]}]
[2023-01-04 04:11:53,828] {python.py:173} INFO - Done. Returned value was: None
[2023-01-04 04:11:53,846] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=populate_crypto_values, task_id=get_crypto_values, execution_date=20210102T070000, start_date=20230104T071152, end_date=20230104T071153
[2023-01-04 04:11:53,882] {local_task_job.py:156} INFO - Task exited with return code 0
[2023-01-04 04:11:53,907] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-01-04 05:07:35,229] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: populate_crypto_values.get_crypto_values scheduled__2021-01-02T07:00:00+00:00 [queued]>
[2023-01-04 05:07:35,298] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: populate_crypto_values.get_crypto_values scheduled__2021-01-02T07:00:00+00:00 [queued]>
[2023-01-04 05:07:35,298] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-01-04 05:07:35,298] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2023-01-04 05:07:35,298] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-01-04 05:07:35,312] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): get_crypto_values> on 2021-01-02 07:00:00+00:00
[2023-01-04 05:07:35,317] {standard_task_runner.py:52} INFO - Started process 5318 to run task
[2023-01-04 05:07:35,323] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'populate_crypto_values', 'get_crypto_values', 'scheduled__2021-01-02T07:00:00+00:00', '--job-id', '57', '--raw', '--subdir', 'DAGS_FOLDER/populate_crypto_values.py', '--cfg-path', '/tmp/tmpatc8rl5n', '--error-file', '/tmp/tmpyfae9qay']
[2023-01-04 05:07:35,324] {standard_task_runner.py:80} INFO - Job 57: Subtask get_crypto_values
[2023-01-04 05:07:35,395] {task_command.py:370} INFO - Running <TaskInstance: populate_crypto_values.get_crypto_values scheduled__2021-01-02T07:00:00+00:00 [running]> on host xuxon-virtual-machine
[2023-01-04 05:07:35,472] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=populate_crypto_values
AIRFLOW_CTX_TASK_ID=get_crypto_values
AIRFLOW_CTX_EXECUTION_DATE=2021-01-02T07:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-01-02T07:00:00+00:00
[2023-01-04 05:07:37,329] {logging_mixin.py:115} INFO - Encountered errors while inserting rows: [{'index': 0, 'errors': [{'reason': 'invalid', 'location': 'snapshot_date', 'debugInfo': '', 'message': "Invalid date: '03-01-2021'"}]}, {'index': 1, 'errors': [{'reason': 'invalid', 'location': 'snapshot_date', 'debugInfo': '', 'message': "Invalid date: '03-01-2021'"}]}]
[2023-01-04 05:07:37,329] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/xuxon/Documents/airflow_case/venv/lib/python3.8/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/xuxon/Documents/airflow_case/venv/lib/python3.8/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/xuxon/Documents/airflow_case/dags/populate_crypto_values.py", line 87, in get_crypto_values_func
    raise Exception('Could not insert the values for this date')
Exception: Could not insert the values for this date
[2023-01-04 05:07:37,334] {taskinstance.py:1395} INFO - Marking task as FAILED. dag_id=populate_crypto_values, task_id=get_crypto_values, execution_date=20210102T070000, start_date=20230104T080735, end_date=20230104T080737
[2023-01-04 05:07:37,351] {standard_task_runner.py:92} ERROR - Failed to execute job 57 for task get_crypto_values (Could not insert the values for this date; 5318)
[2023-01-04 05:07:37,400] {local_task_job.py:156} INFO - Task exited with return code 1
[2023-01-04 05:07:37,427] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-01-04 05:11:33,187] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: populate_crypto_values.get_crypto_values scheduled__2021-01-02T07:00:00+00:00 [queued]>
[2023-01-04 05:11:33,195] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: populate_crypto_values.get_crypto_values scheduled__2021-01-02T07:00:00+00:00 [queued]>
[2023-01-04 05:11:33,195] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-01-04 05:11:33,196] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2023-01-04 05:11:33,196] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-01-04 05:11:33,211] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): get_crypto_values> on 2021-01-02 07:00:00+00:00
[2023-01-04 05:11:33,215] {standard_task_runner.py:52} INFO - Started process 6522 to run task
[2023-01-04 05:11:33,221] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'populate_crypto_values', 'get_crypto_values', 'scheduled__2021-01-02T07:00:00+00:00', '--job-id', '59', '--raw', '--subdir', 'DAGS_FOLDER/populate_crypto_values.py', '--cfg-path', '/tmp/tmpzz5fwrrf', '--error-file', '/tmp/tmp46e1t2ix']
[2023-01-04 05:11:33,222] {standard_task_runner.py:80} INFO - Job 59: Subtask get_crypto_values
[2023-01-04 05:11:33,283] {task_command.py:370} INFO - Running <TaskInstance: populate_crypto_values.get_crypto_values scheduled__2021-01-02T07:00:00+00:00 [running]> on host xuxon-virtual-machine
[2023-01-04 05:11:33,352] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=populate_crypto_values
AIRFLOW_CTX_TASK_ID=get_crypto_values
AIRFLOW_CTX_EXECUTION_DATE=2021-01-02T07:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-01-02T07:00:00+00:00
[2023-01-04 05:11:34,253] {logging_mixin.py:115} INFO - New rows have been added.
[2023-01-04 05:11:34,253] {python.py:173} INFO - Done. Returned value was: None
[2023-01-04 05:11:34,304] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=populate_crypto_values, task_id=get_crypto_values, execution_date=20210102T070000, start_date=20230104T081133, end_date=20230104T081134
[2023-01-04 05:11:34,370] {local_task_job.py:156} INFO - Task exited with return code 0
[2023-01-04 05:11:34,402] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
