[2023-01-04 13:20:48,158] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: populate_crypto_values.get_crypto_values scheduled__2022-06-07T07:00:00+00:00 [queued]>
[2023-01-04 13:20:48,164] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: populate_crypto_values.get_crypto_values scheduled__2022-06-07T07:00:00+00:00 [queued]>
[2023-01-04 13:20:48,164] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-01-04 13:20:48,165] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2023-01-04 13:20:48,165] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-01-04 13:20:48,179] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): get_crypto_values> on 2022-06-07 07:00:00+00:00
[2023-01-04 13:20:48,184] {standard_task_runner.py:52} INFO - Started process 29122 to run task
[2023-01-04 13:20:48,189] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'populate_crypto_values', 'get_crypto_values', 'scheduled__2022-06-07T07:00:00+00:00', '--job-id', '583', '--raw', '--subdir', 'DAGS_FOLDER/populate_crypto_values.py', '--cfg-path', '/tmp/tmpp1i5n48y', '--error-file', '/tmp/tmpfmle9knc']
[2023-01-04 13:20:48,190] {standard_task_runner.py:80} INFO - Job 583: Subtask get_crypto_values
[2023-01-04 13:20:48,261] {task_command.py:370} INFO - Running <TaskInstance: populate_crypto_values.get_crypto_values scheduled__2022-06-07T07:00:00+00:00 [running]> on host xuxon-virtual-machine
[2023-01-04 13:20:48,338] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=populate_crypto_values
AIRFLOW_CTX_TASK_ID=get_crypto_values
AIRFLOW_CTX_EXECUTION_DATE=2022-06-07T07:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-06-07T07:00:00+00:00
[2023-01-04 13:20:48,437] {logging_mixin.py:115} INFO - Attempt 1 to get the crypto values has failed. The api status was 429
[2023-01-04 13:20:48,438] {logging_mixin.py:115} INFO - The api response was {"status":{"error_code":429,"error_message":"You've exceeded the Rate Limit. Please visit https://www.coingecko.com/en/api/pricing to subscribe to our API plans for higher rate limits."}}
[2023-01-04 13:21:03,543] {logging_mixin.py:115} INFO - Attempt 2 to get the crypto values has failed. The api status was 429
[2023-01-04 13:21:03,544] {logging_mixin.py:115} INFO - The api response was {"status":{"error_code":429,"error_message":"You've exceeded the Rate Limit. Please visit https://www.coingecko.com/en/api/pricing to subscribe to our API plans for higher rate limits."}}
[2023-01-04 13:21:18,679] {logging_mixin.py:115} INFO - Attempt 3 to get the crypto values has failed. The api status was 429
[2023-01-04 13:21:18,680] {logging_mixin.py:115} INFO - The api response was {"status":{"error_code":429,"error_message":"You've exceeded the Rate Limit. Please visit https://www.coingecko.com/en/api/pricing to subscribe to our API plans for higher rate limits."}}
[2023-01-04 13:21:33,789] {logging_mixin.py:115} INFO - Attempt 4 to get the crypto values has failed. The api status was 429
[2023-01-04 13:21:33,790] {logging_mixin.py:115} INFO - The api response was {"status":{"error_code":429,"error_message":"You've exceeded the Rate Limit. Please visit https://www.coingecko.com/en/api/pricing to subscribe to our API plans for higher rate limits."}}
[2023-01-04 13:21:48,904] {logging_mixin.py:115} INFO - Attempt 5 to get the crypto values has failed. The api status was 429
[2023-01-04 13:21:48,904] {logging_mixin.py:115} INFO - The api response was {"status":{"error_code":429,"error_message":"You've exceeded the Rate Limit. Please visit https://www.coingecko.com/en/api/pricing to subscribe to our API plans for higher rate limits."}}
[2023-01-04 13:22:04,019] {logging_mixin.py:115} INFO - Attempt 6 to get the crypto values has failed. The api status was 429
[2023-01-04 13:22:04,020] {logging_mixin.py:115} INFO - The api response was {"status":{"error_code":429,"error_message":"You've exceeded the Rate Limit. Please visit https://www.coingecko.com/en/api/pricing to subscribe to our API plans for higher rate limits."}}
[2023-01-04 13:22:19,159] {logging_mixin.py:115} INFO - Attempt 7 to get the crypto values has failed. The api status was 429
[2023-01-04 13:22:19,160] {logging_mixin.py:115} INFO - The api response was {"status":{"error_code":429,"error_message":"You've exceeded the Rate Limit. Please visit https://www.coingecko.com/en/api/pricing to subscribe to our API plans for higher rate limits."}}
[2023-01-04 13:22:34,290] {logging_mixin.py:115} INFO - Attempt 8 to get the crypto values has failed. The api status was 429
[2023-01-04 13:22:34,292] {logging_mixin.py:115} INFO - The api response was {"status":{"error_code":429,"error_message":"You've exceeded the Rate Limit. Please visit https://www.coingecko.com/en/api/pricing to subscribe to our API plans for higher rate limits."}}
[2023-01-04 13:22:50,810] {logging_mixin.py:115} INFO - New rows have been added.
[2023-01-04 13:22:50,811] {python.py:173} INFO - Done. Returned value was: None
[2023-01-04 13:22:50,818] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=populate_crypto_values, task_id=get_crypto_values, execution_date=20220607T070000, start_date=20230104T162048, end_date=20230104T162250
[2023-01-04 13:22:50,848] {local_task_job.py:156} INFO - Task exited with return code 0
[2023-01-04 13:22:50,866] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
