[2023-01-04 06:10:01,237] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: populate_crypto_values.get_crypto_values scheduled__2021-08-29T07:00:00+00:00 [queued]>
[2023-01-04 06:10:01,243] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: populate_crypto_values.get_crypto_values scheduled__2021-08-29T07:00:00+00:00 [queued]>
[2023-01-04 06:10:01,243] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-01-04 06:10:01,244] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2023-01-04 06:10:01,244] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-01-04 06:10:01,256] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): get_crypto_values> on 2021-08-29 07:00:00+00:00
[2023-01-04 06:10:01,261] {standard_task_runner.py:52} INFO - Started process 17235 to run task
[2023-01-04 06:10:01,267] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'populate_crypto_values', 'get_crypto_values', 'scheduled__2021-08-29T07:00:00+00:00', '--job-id', '298', '--raw', '--subdir', 'DAGS_FOLDER/populate_crypto_values.py', '--cfg-path', '/tmp/tmpnjs96uoe', '--error-file', '/tmp/tmpc1uji46j']
[2023-01-04 06:10:01,268] {standard_task_runner.py:80} INFO - Job 298: Subtask get_crypto_values
[2023-01-04 06:10:01,362] {task_command.py:370} INFO - Running <TaskInstance: populate_crypto_values.get_crypto_values scheduled__2021-08-29T07:00:00+00:00 [running]> on host xuxon-virtual-machine
[2023-01-04 06:10:01,448] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=populate_crypto_values
AIRFLOW_CTX_TASK_ID=get_crypto_values
AIRFLOW_CTX_EXECUTION_DATE=2021-08-29T07:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-08-29T07:00:00+00:00
[2023-01-04 06:10:32,848] {logging_mixin.py:115} INFO - Attempt 1 to get the crypto values has failed. The api status was 503
[2023-01-04 06:10:32,849] {logging_mixin.py:115} INFO - The api response was {"status":503,"error":"Service Unavailable"}
[2023-01-04 06:10:48,567] {logging_mixin.py:115} INFO - New rows have been added.
[2023-01-04 06:10:48,568] {python.py:173} INFO - Done. Returned value was: None
[2023-01-04 06:10:48,577] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=populate_crypto_values, task_id=get_crypto_values, execution_date=20210829T070000, start_date=20230104T091001, end_date=20230104T091048
[2023-01-04 06:10:48,621] {local_task_job.py:156} INFO - Task exited with return code 0
[2023-01-04 06:10:48,653] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
