[2023-01-04 12:41:36,228] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: populate_crypto_values.get_crypto_values scheduled__2022-01-05T07:00:00+00:00 [queued]>
[2023-01-04 12:41:36,234] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: populate_crypto_values.get_crypto_values scheduled__2022-01-05T07:00:00+00:00 [queued]>
[2023-01-04 12:41:36,235] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-01-04 12:41:36,235] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2023-01-04 12:41:36,235] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-01-04 12:41:36,247] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): get_crypto_values> on 2022-01-05 07:00:00+00:00
[2023-01-04 12:41:36,251] {standard_task_runner.py:52} INFO - Started process 24931 to run task
[2023-01-04 12:41:36,257] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'populate_crypto_values', 'get_crypto_values', 'scheduled__2022-01-05T07:00:00+00:00', '--job-id', '430', '--raw', '--subdir', 'DAGS_FOLDER/populate_crypto_values.py', '--cfg-path', '/tmp/tmpstymji2y', '--error-file', '/tmp/tmpoog6j4si']
[2023-01-04 12:41:36,258] {standard_task_runner.py:80} INFO - Job 430: Subtask get_crypto_values
[2023-01-04 12:41:36,308] {task_command.py:370} INFO - Running <TaskInstance: populate_crypto_values.get_crypto_values scheduled__2022-01-05T07:00:00+00:00 [running]> on host xuxon-virtual-machine
[2023-01-04 12:41:36,371] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=populate_crypto_values
AIRFLOW_CTX_TASK_ID=get_crypto_values
AIRFLOW_CTX_EXECUTION_DATE=2022-01-05T07:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-01-05T07:00:00+00:00
[2023-01-04 12:41:36,958] {logging_mixin.py:115} INFO - Attempt 1 to get the crypto values has failed. The api status was 429
[2023-01-04 12:41:36,959] {logging_mixin.py:115} INFO - The api response was {"status":{"error_code":429,"error_message":"You've exceeded the Rate Limit. Please visit https://www.coingecko.com/en/api/pricing to subscribe to our API plans for higher rate limits."}}
[2023-01-04 12:41:52,086] {logging_mixin.py:115} INFO - Attempt 2 to get the crypto values has failed. The api status was 429
[2023-01-04 12:41:52,087] {logging_mixin.py:115} INFO - The api response was {"status":{"error_code":429,"error_message":"You've exceeded the Rate Limit. Please visit https://www.coingecko.com/en/api/pricing to subscribe to our API plans for higher rate limits."}}
[2023-01-04 12:42:07,191] {logging_mixin.py:115} INFO - Attempt 3 to get the crypto values has failed. The api status was 429
[2023-01-04 12:42:07,192] {logging_mixin.py:115} INFO - The api response was {"status":{"error_code":429,"error_message":"You've exceeded the Rate Limit. Please visit https://www.coingecko.com/en/api/pricing to subscribe to our API plans for higher rate limits."}}
[2023-01-04 12:42:22,285] {logging_mixin.py:115} INFO - Attempt 4 to get the crypto values has failed. The api status was 429
[2023-01-04 12:42:22,288] {logging_mixin.py:115} INFO - The api response was {"status":{"error_code":429,"error_message":"You've exceeded the Rate Limit. Please visit https://www.coingecko.com/en/api/pricing to subscribe to our API plans for higher rate limits."}}
[2023-01-04 12:42:37,409] {logging_mixin.py:115} INFO - Attempt 5 to get the crypto values has failed. The api status was 429
[2023-01-04 12:42:37,409] {logging_mixin.py:115} INFO - The api response was {"status":{"error_code":429,"error_message":"You've exceeded the Rate Limit. Please visit https://www.coingecko.com/en/api/pricing to subscribe to our API plans for higher rate limits."}}
[2023-01-04 12:42:52,543] {logging_mixin.py:115} INFO - Attempt 6 to get the crypto values has failed. The api status was 429
[2023-01-04 12:42:52,544] {logging_mixin.py:115} INFO - The api response was {"status":{"error_code":429,"error_message":"You've exceeded the Rate Limit. Please visit https://www.coingecko.com/en/api/pricing to subscribe to our API plans for higher rate limits."}}
[2023-01-04 12:43:07,665] {logging_mixin.py:115} INFO - Attempt 7 to get the crypto values has failed. The api status was 429
[2023-01-04 12:43:07,666] {logging_mixin.py:115} INFO - The api response was {"status":{"error_code":429,"error_message":"You've exceeded the Rate Limit. Please visit https://www.coingecko.com/en/api/pricing to subscribe to our API plans for higher rate limits."}}
[2023-01-04 12:43:22,774] {logging_mixin.py:115} INFO - Attempt 8 to get the crypto values has failed. The api status was 429
[2023-01-04 12:43:22,774] {logging_mixin.py:115} INFO - The api response was {"status":{"error_code":429,"error_message":"You've exceeded the Rate Limit. Please visit https://www.coingecko.com/en/api/pricing to subscribe to our API plans for higher rate limits."}}
[2023-01-04 12:43:38,907] {logging_mixin.py:115} INFO - New rows have been added.
[2023-01-04 12:43:38,908] {python.py:173} INFO - Done. Returned value was: None
[2023-01-04 12:43:38,926] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=populate_crypto_values, task_id=get_crypto_values, execution_date=20220105T070000, start_date=20230104T154136, end_date=20230104T154338
[2023-01-04 12:43:38,975] {local_task_job.py:156} INFO - Task exited with return code 0
[2023-01-04 12:43:38,988] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
