[2023-01-04 13:43:08,648] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: populate_crypto_values.get_crypto_values scheduled__2022-09-12T07:00:00+00:00 [queued]>
[2023-01-04 13:43:08,656] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: populate_crypto_values.get_crypto_values scheduled__2022-09-12T07:00:00+00:00 [queued]>
[2023-01-04 13:43:08,656] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-01-04 13:43:08,656] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2023-01-04 13:43:08,656] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-01-04 13:43:08,669] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): get_crypto_values> on 2022-09-12 07:00:00+00:00
[2023-01-04 13:43:08,673] {standard_task_runner.py:52} INFO - Started process 31562 to run task
[2023-01-04 13:43:08,679] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'populate_crypto_values', 'get_crypto_values', 'scheduled__2022-09-12T07:00:00+00:00', '--job-id', '680', '--raw', '--subdir', 'DAGS_FOLDER/populate_crypto_values.py', '--cfg-path', '/tmp/tmpszj5htfq', '--error-file', '/tmp/tmpgc9g6ch_']
[2023-01-04 13:43:08,680] {standard_task_runner.py:80} INFO - Job 680: Subtask get_crypto_values
[2023-01-04 13:43:08,732] {task_command.py:370} INFO - Running <TaskInstance: populate_crypto_values.get_crypto_values scheduled__2022-09-12T07:00:00+00:00 [running]> on host xuxon-virtual-machine
[2023-01-04 13:43:08,866] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=populate_crypto_values
AIRFLOW_CTX_TASK_ID=get_crypto_values
AIRFLOW_CTX_EXECUTION_DATE=2022-09-12T07:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-09-12T07:00:00+00:00
[2023-01-04 13:43:08,969] {logging_mixin.py:115} INFO - Attempt 1 to get the crypto values has failed. The api status was 429
[2023-01-04 13:43:08,969] {logging_mixin.py:115} INFO - The api response was {"status":{"error_code":429,"error_message":"You've exceeded the Rate Limit. Please visit https://www.coingecko.com/en/api/pricing to subscribe to our API plans for higher rate limits."}}
[2023-01-04 13:43:24,089] {logging_mixin.py:115} INFO - Attempt 2 to get the crypto values has failed. The api status was 429
[2023-01-04 13:43:24,089] {logging_mixin.py:115} INFO - The api response was {"status":{"error_code":429,"error_message":"You've exceeded the Rate Limit. Please visit https://www.coingecko.com/en/api/pricing to subscribe to our API plans for higher rate limits."}}
[2023-01-04 13:43:39,228] {logging_mixin.py:115} INFO - Attempt 3 to get the crypto values has failed. The api status was 429
[2023-01-04 13:43:39,228] {logging_mixin.py:115} INFO - The api response was {"status":{"error_code":429,"error_message":"You've exceeded the Rate Limit. Please visit https://www.coingecko.com/en/api/pricing to subscribe to our API plans for higher rate limits."}}
[2023-01-04 13:43:54,339] {logging_mixin.py:115} INFO - Attempt 4 to get the crypto values has failed. The api status was 429
[2023-01-04 13:43:54,339] {logging_mixin.py:115} INFO - The api response was {"status":{"error_code":429,"error_message":"You've exceeded the Rate Limit. Please visit https://www.coingecko.com/en/api/pricing to subscribe to our API plans for higher rate limits."}}
[2023-01-04 13:44:09,442] {logging_mixin.py:115} INFO - Attempt 5 to get the crypto values has failed. The api status was 429
[2023-01-04 13:44:09,442] {logging_mixin.py:115} INFO - The api response was {"status":{"error_code":429,"error_message":"You've exceeded the Rate Limit. Please visit https://www.coingecko.com/en/api/pricing to subscribe to our API plans for higher rate limits."}}
[2023-01-04 13:44:24,556] {logging_mixin.py:115} INFO - Attempt 6 to get the crypto values has failed. The api status was 429
[2023-01-04 13:44:24,556] {logging_mixin.py:115} INFO - The api response was {"status":{"error_code":429,"error_message":"You've exceeded the Rate Limit. Please visit https://www.coingecko.com/en/api/pricing to subscribe to our API plans for higher rate limits."}}
[2023-01-04 13:44:39,664] {logging_mixin.py:115} INFO - Attempt 7 to get the crypto values has failed. The api status was 429
[2023-01-04 13:44:39,664] {logging_mixin.py:115} INFO - The api response was {"status":{"error_code":429,"error_message":"You've exceeded the Rate Limit. Please visit https://www.coingecko.com/en/api/pricing to subscribe to our API plans for higher rate limits."}}
[2023-01-04 13:44:54,800] {logging_mixin.py:115} INFO - Attempt 8 to get the crypto values has failed. The api status was 429
[2023-01-04 13:44:54,801] {logging_mixin.py:115} INFO - The api response was {"status":{"error_code":429,"error_message":"You've exceeded the Rate Limit. Please visit https://www.coingecko.com/en/api/pricing to subscribe to our API plans for higher rate limits."}}
[2023-01-04 13:45:10,960] {logging_mixin.py:115} INFO - New rows have been added.
[2023-01-04 13:45:10,961] {python.py:173} INFO - Done. Returned value was: None
[2023-01-04 13:45:10,983] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=populate_crypto_values, task_id=get_crypto_values, execution_date=20220912T070000, start_date=20230104T164308, end_date=20230104T164510
[2023-01-04 13:45:11,051] {local_task_job.py:156} INFO - Task exited with return code 0
[2023-01-04 13:45:11,082] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
