[2023-01-04 05:29:59,485] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: populate_crypto_values.get_crypto_values scheduled__2021-03-15T07:00:00+00:00 [queued]>
[2023-01-04 05:29:59,492] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: populate_crypto_values.get_crypto_values scheduled__2021-03-15T07:00:00+00:00 [queued]>
[2023-01-04 05:29:59,492] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-01-04 05:29:59,492] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2023-01-04 05:29:59,492] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-01-04 05:29:59,506] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): get_crypto_values> on 2021-03-15 07:00:00+00:00
[2023-01-04 05:29:59,511] {standard_task_runner.py:52} INFO - Started process 9690 to run task
[2023-01-04 05:29:59,516] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'populate_crypto_values', 'get_crypto_values', 'scheduled__2021-03-15T07:00:00+00:00', '--job-id', '131', '--raw', '--subdir', 'DAGS_FOLDER/populate_crypto_values.py', '--cfg-path', '/tmp/tmp23vxko95', '--error-file', '/tmp/tmpyg21exvs']
[2023-01-04 05:29:59,518] {standard_task_runner.py:80} INFO - Job 131: Subtask get_crypto_values
[2023-01-04 05:29:59,572] {task_command.py:370} INFO - Running <TaskInstance: populate_crypto_values.get_crypto_values scheduled__2021-03-15T07:00:00+00:00 [running]> on host xuxon-virtual-machine
[2023-01-04 05:29:59,654] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=populate_crypto_values
AIRFLOW_CTX_TASK_ID=get_crypto_values
AIRFLOW_CTX_EXECUTION_DATE=2021-03-15T07:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-03-15T07:00:00+00:00
[2023-01-04 05:30:30,281] {logging_mixin.py:115} INFO - Attempt 1 to get the crypto values has failed. The api status was 503
[2023-01-04 05:30:30,282] {logging_mixin.py:115} INFO - The api response was {"status":503,"error":"Service Unavailable"}
[2023-01-04 05:30:46,037] {logging_mixin.py:115} INFO - New rows have been added.
[2023-01-04 05:30:46,038] {python.py:173} INFO - Done. Returned value was: None
[2023-01-04 05:30:46,058] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=populate_crypto_values, task_id=get_crypto_values, execution_date=20210315T070000, start_date=20230104T082959, end_date=20230104T083046
[2023-01-04 05:30:46,098] {local_task_job.py:156} INFO - Task exited with return code 0
[2023-01-04 05:30:46,110] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
