[2023-01-04 03:46:14,681] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: populate_crypto_values.get_crypto_values scheduled__2021-01-01T07:00:00+00:00 [queued]>
[2023-01-04 03:46:14,695] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: populate_crypto_values.get_crypto_values scheduled__2021-01-01T07:00:00+00:00 [queued]>
[2023-01-04 03:46:14,695] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-01-04 03:46:14,695] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2023-01-04 03:46:14,695] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-01-04 03:46:14,719] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): get_crypto_values> on 2021-01-01 07:00:00+00:00
[2023-01-04 03:46:14,725] {standard_task_runner.py:52} INFO - Started process 58125 to run task
[2023-01-04 03:46:14,882] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'populate_crypto_values', 'get_crypto_values', 'scheduled__2021-01-01T07:00:00+00:00', '--job-id', '29', '--raw', '--subdir', 'DAGS_FOLDER/populate_crypto_values.py', '--cfg-path', '/tmp/tmpwc0ogk5v', '--error-file', '/tmp/tmpajuvqf4k']
[2023-01-04 03:46:14,884] {standard_task_runner.py:80} INFO - Job 29: Subtask get_crypto_values
[2023-01-04 03:46:15,150] {task_command.py:370} INFO - Running <TaskInstance: populate_crypto_values.get_crypto_values scheduled__2021-01-01T07:00:00+00:00 [running]> on host xuxon-virtual-machine
[2023-01-04 03:46:15,958] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=populate_crypto_values
AIRFLOW_CTX_TASK_ID=get_crypto_values
AIRFLOW_CTX_EXECUTION_DATE=2021-01-01T07:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-01-01T07:00:00+00:00
[2023-01-04 03:46:19,028] {logging_mixin.py:115} INFO - New rows have been added.
[2023-01-04 03:46:19,028] {python.py:173} INFO - Done. Returned value was: None
[2023-01-04 03:46:19,038] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=populate_crypto_values, task_id=get_crypto_values, execution_date=20210101T070000, start_date=20230104T064614, end_date=20230104T064619
[2023-01-04 03:46:19,338] {local_task_job.py:156} INFO - Task exited with return code 0
[2023-01-04 03:46:19,385] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-01-04 04:11:47,685] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: populate_crypto_values.get_crypto_values scheduled__2021-01-01T07:00:00+00:00 [queued]>
[2023-01-04 04:11:47,700] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: populate_crypto_values.get_crypto_values scheduled__2021-01-01T07:00:00+00:00 [queued]>
[2023-01-04 04:11:47,700] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-01-04 04:11:47,700] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2023-01-04 04:11:47,700] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-01-04 04:11:47,714] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): get_crypto_values> on 2021-01-01 07:00:00+00:00
[2023-01-04 04:11:47,718] {standard_task_runner.py:52} INFO - Started process 62217 to run task
[2023-01-04 04:11:47,724] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'populate_crypto_values', 'get_crypto_values', 'scheduled__2021-01-01T07:00:00+00:00', '--job-id', '29', '--raw', '--subdir', 'DAGS_FOLDER/populate_crypto_values.py', '--cfg-path', '/tmp/tmpgwj58v30', '--error-file', '/tmp/tmpl_ugv7hq']
[2023-01-04 04:11:47,725] {standard_task_runner.py:80} INFO - Job 29: Subtask get_crypto_values
[2023-01-04 04:11:47,806] {task_command.py:370} INFO - Running <TaskInstance: populate_crypto_values.get_crypto_values scheduled__2021-01-01T07:00:00+00:00 [running]> on host xuxon-virtual-machine
[2023-01-04 04:11:47,882] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=populate_crypto_values
AIRFLOW_CTX_TASK_ID=get_crypto_values
AIRFLOW_CTX_EXECUTION_DATE=2021-01-01T07:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-01-01T07:00:00+00:00
[2023-01-04 04:11:49,089] {logging_mixin.py:115} INFO - Encountered errors while inserting rows: [{'index': 0, 'errors': [{'reason': 'invalid', 'location': 'snapshot_date', 'debugInfo': '', 'message': "Invalid date: '02-01-2021'"}]}, {'index': 1, 'errors': [{'reason': 'invalid', 'location': 'snapshot_date', 'debugInfo': '', 'message': "Invalid date: '02-01-2021'"}]}]
[2023-01-04 04:11:49,090] {python.py:173} INFO - Done. Returned value was: None
[2023-01-04 04:11:49,102] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=populate_crypto_values, task_id=get_crypto_values, execution_date=20210101T070000, start_date=20230104T071147, end_date=20230104T071149
[2023-01-04 04:11:49,150] {local_task_job.py:156} INFO - Task exited with return code 0
[2023-01-04 04:11:49,175] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-01-04 05:07:30,426] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: populate_crypto_values.get_crypto_values scheduled__2021-01-01T07:00:00+00:00 [queued]>
[2023-01-04 05:07:30,447] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: populate_crypto_values.get_crypto_values scheduled__2021-01-01T07:00:00+00:00 [queued]>
[2023-01-04 05:07:30,447] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-01-04 05:07:30,447] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2023-01-04 05:07:30,447] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-01-04 05:07:30,469] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): get_crypto_values> on 2021-01-01 07:00:00+00:00
[2023-01-04 05:07:30,480] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'populate_crypto_values', 'get_crypto_values', 'scheduled__2021-01-01T07:00:00+00:00', '--job-id', '56', '--raw', '--subdir', 'DAGS_FOLDER/populate_crypto_values.py', '--cfg-path', '/tmp/tmpa9049bum', '--error-file', '/tmp/tmpwabxouh2']
[2023-01-04 05:07:30,482] {standard_task_runner.py:80} INFO - Job 56: Subtask get_crypto_values
[2023-01-04 05:07:30,473] {standard_task_runner.py:52} INFO - Started process 5296 to run task
[2023-01-04 05:07:30,732] {task_command.py:370} INFO - Running <TaskInstance: populate_crypto_values.get_crypto_values scheduled__2021-01-01T07:00:00+00:00 [running]> on host xuxon-virtual-machine
[2023-01-04 05:07:30,894] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=populate_crypto_values
AIRFLOW_CTX_TASK_ID=get_crypto_values
AIRFLOW_CTX_EXECUTION_DATE=2021-01-01T07:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-01-01T07:00:00+00:00
[2023-01-04 05:07:32,290] {logging_mixin.py:115} INFO - Encountered errors while inserting rows: [{'index': 0, 'errors': [{'reason': 'invalid', 'location': 'snapshot_date', 'debugInfo': '', 'message': "Invalid date: '02-01-2021'"}]}, {'index': 1, 'errors': [{'reason': 'invalid', 'location': 'snapshot_date', 'debugInfo': '', 'message': "Invalid date: '02-01-2021'"}]}]
[2023-01-04 05:07:32,291] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/xuxon/Documents/airflow_case/venv/lib/python3.8/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/xuxon/Documents/airflow_case/venv/lib/python3.8/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/xuxon/Documents/airflow_case/dags/populate_crypto_values.py", line 87, in get_crypto_values_func
    raise Exception('Could not insert the values for this date')
Exception: Could not insert the values for this date
[2023-01-04 05:07:32,304] {taskinstance.py:1395} INFO - Marking task as FAILED. dag_id=populate_crypto_values, task_id=get_crypto_values, execution_date=20210101T070000, start_date=20230104T080730, end_date=20230104T080732
[2023-01-04 05:07:32,333] {standard_task_runner.py:92} ERROR - Failed to execute job 56 for task get_crypto_values (Could not insert the values for this date; 5296)
[2023-01-04 05:07:32,369] {local_task_job.py:156} INFO - Task exited with return code 1
[2023-01-04 05:07:32,395] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-01-04 05:11:28,825] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: populate_crypto_values.get_crypto_values scheduled__2021-01-01T07:00:00+00:00 [queued]>
[2023-01-04 05:11:28,835] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: populate_crypto_values.get_crypto_values scheduled__2021-01-01T07:00:00+00:00 [queued]>
[2023-01-04 05:11:28,835] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2023-01-04 05:11:28,835] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2023-01-04 05:11:28,835] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2023-01-04 05:11:28,851] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): get_crypto_values> on 2021-01-01 07:00:00+00:00
[2023-01-04 05:11:28,855] {standard_task_runner.py:52} INFO - Started process 6503 to run task
[2023-01-04 05:11:28,861] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'populate_crypto_values', 'get_crypto_values', 'scheduled__2021-01-01T07:00:00+00:00', '--job-id', '58', '--raw', '--subdir', 'DAGS_FOLDER/populate_crypto_values.py', '--cfg-path', '/tmp/tmpy7chwfvz', '--error-file', '/tmp/tmphgr0hqkj']
[2023-01-04 05:11:28,862] {standard_task_runner.py:80} INFO - Job 58: Subtask get_crypto_values
[2023-01-04 05:11:29,416] {task_command.py:370} INFO - Running <TaskInstance: populate_crypto_values.get_crypto_values scheduled__2021-01-01T07:00:00+00:00 [running]> on host xuxon-virtual-machine
[2023-01-04 05:11:29,539] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=populate_crypto_values
AIRFLOW_CTX_TASK_ID=get_crypto_values
AIRFLOW_CTX_EXECUTION_DATE=2021-01-01T07:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-01-01T07:00:00+00:00
[2023-01-04 05:11:30,411] {logging_mixin.py:115} INFO - New rows have been added.
[2023-01-04 05:11:30,412] {python.py:173} INFO - Done. Returned value was: None
[2023-01-04 05:11:30,430] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=populate_crypto_values, task_id=get_crypto_values, execution_date=20210101T070000, start_date=20230104T081128, end_date=20230104T081130
[2023-01-04 05:11:30,490] {local_task_job.py:156} INFO - Task exited with return code 0
[2023-01-04 05:11:30,516] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
